// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHQO8hEoXj8hC-JpL3Z2Ef8Hei0iP2Mw',
    appId: '1:649773396191:web:9aad719246b9b810fef96a',
    messagingSenderId: '649773396191',
    projectId: 'my-first-app-1becf',
    authDomain: 'my-first-app-1becf.firebaseapp.com',
    storageBucket: 'my-first-app-1becf.appspot.com',
    measurementId: 'G-JK26VCCH6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUqczhuREN6nyWGyvgffljBPtzWTkni7k',
    appId: '1:649773396191:android:4ca36ad23e253cb1fef96a',
    messagingSenderId: '649773396191',
    projectId: 'my-first-app-1becf',
    storageBucket: 'my-first-app-1becf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxKK17EH7XweeGkewijOsKKn4wRI5Z0w',
    appId: '1:649773396191:ios:c7ccaa1400933c73fef96a',
    messagingSenderId: '649773396191',
    projectId: 'my-first-app-1becf',
    storageBucket: 'my-first-app-1becf.appspot.com',
    iosClientId: '649773396191-6akmm6qu6dooguk2k573k6dbjjcehjeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
